### ISSUE TITLE
[BACK] Add new endpoint to delete an user

### ISSUE THREAD

**Issue by LeTrovoes** [PokerTeamUFABC/BrieflyPlanningPoker#2]
upstream issue: https://github.com/AsyncPlanningPoker/BrieflyPlanningPoker/issues/103

TO-DO

- [x] Store - Create new deleteByEmail interface (method itself already exists)
- [x] API - Create a new delete endpoint (/users) with authorization middleware

**Comment by rafaelhs-debug** [comment]
Ambiente Configurado e funções das APIs criadas. Amanhã vamos continuar o trabalho

**Comment by igorney** [comment]
![image](https://user-images.githubusercontent.com/48994130/196582787-56e51c35-376b-4035-8ac4-1289408020c5.png)
![image](https://user-images.githubusercontent.com/48994130/196582801-f688e7f7-3397-461e-b7a0-41de0b6c34f0.png)
Resultado dos Testes locais.
